// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBVkR-z2lI0kGXtf8ZA7s6HF5ME_cbcQA',
    appId: '1:112722249195:web:6ccbe08860d0d5623b45ae',
    messagingSenderId: '112722249195',
    projectId: 'manajemen-waktu-app',
    authDomain: 'manajemen-waktu-app.firebaseapp.com',
    storageBucket: 'manajemen-waktu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWe1UKZOfrl_JG__OVpO7I2H2yoWAkSU',
    appId: '1:112722249195:android:247e8b3777333b833b45ae',
    messagingSenderId: '112722249195',
    projectId: 'manajemen-waktu-app',
    storageBucket: 'manajemen-waktu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0KcM5rdEEBOTGAXnbCDxcjH2N1CwFBxA',
    appId: '1:112722249195:ios:2c9290f46c20725d3b45ae',
    messagingSenderId: '112722249195',
    projectId: 'manajemen-waktu-app',
    storageBucket: 'manajemen-waktu-app.firebasestorage.app',
    iosBundleId: 'com.example.manajemenWaktu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0KcM5rdEEBOTGAXnbCDxcjH2N1CwFBxA',
    appId: '1:112722249195:ios:2c9290f46c20725d3b45ae',
    messagingSenderId: '112722249195',
    projectId: 'manajemen-waktu-app',
    storageBucket: 'manajemen-waktu-app.firebasestorage.app',
    iosBundleId: 'com.example.manajemenWaktu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBVkR-z2lI0kGXtf8ZA7s6HF5ME_cbcQA',
    appId: '1:112722249195:web:86b8bc2476408aff3b45ae',
    messagingSenderId: '112722249195',
    projectId: 'manajemen-waktu-app',
    authDomain: 'manajemen-waktu-app.firebaseapp.com',
    storageBucket: 'manajemen-waktu-app.firebasestorage.app',
  );

}